/** Shapes shared by the mosaic's build script, server page and canvas. */

import type { WorldPoint } from './geo';

/** One painting's tile, in the same order as the atlas image. */
export interface MosaicTile {
  /** Title as shown (already spaced out; see ./titles). */
  title: string;
  /** The painting's slug, for the link to its page in the collection. */
  slug: string;
  /** Image file name, the same under `web/` and `thumbs/`. */
  file: string;
  /** The painting's average colour, shown until the atlas has loaded. */
  color: string;
}

/** Generated by scripts/mosaic/build-mosaic.ts (src/lib/mosaic/layout.json). */
export interface MosaicLayout {
  /** Side of one square cell, in world units. */
  cellSize: number;
  /** Tiles per row in the atlas image. */
  atlasColumns: number;
  /** Side of one atlas tile, in pixels. */
  atlasTile: number;
  /** Centre of each cell in world units; index-aligned with `tiles`. */
  cells: WorldPoint[];
  tiles: MosaicTile[];
}

/** A named point on the map: a mural, or a cause with a home on the island. */
export interface MosaicPin {
  name: string;
  /** Null when there is nothing to point at on the island. */
  at: WorldPoint | null;
  /** A sentence or two shown when the pin is chosen. */
  text?: string;
}
